# AdGuardHome DNS
# 启用/禁用(true/false)
AGH_ENABLE=true

# AdGuardHome 端口
AGH_DNS_PORT=5300

# AdGuardHome 用户和用户组
AGH_USER=root
AGH_GROUP=net_raw

# 阻断 ipv6 的 DNS 请求
# 启用/禁用(true/false)
BLOCK_IPV6_DNS=true

# SmartDNS
# 启用/禁用(true/false)
SMARTDNS_ENABLE=true

# Tun 网卡
TUN_DEVICE=Meta

# Mihomo DNS 端口
MIHOMO_DNS_PORT=1053

# Mihomo ipv6 代理 
# 启用/禁用(true/false)
MIHOMO_IPV6=true

# 使用 iptables 拦截 ip
# 启用/禁用(true/false)
IP_IPTABLES=false

# host
# 启用/禁用(true/false)
HOST_ENABLE=true

# 定时执行 启用/禁用(true/false)
# 配置路径: /data/adb/modules/SAM/etc/crontabs/root
CRONTAB_ENABLE=false

# Mihomo配置卸载备份 启用/禁用(true/false)
# 存放路径: /sdcard/Mihomo配置.yaml
BACKUP_CONF=true

# 节点订阅地址
# 注意: 地址要用双引号，每个地址之间用空格隔离开来，无订阅则无法启动服务
# 示例: SUB_URL=("订阅地址1" "订阅地址2" "订阅地址3")
SUB_URL=()

# 黑名单App
# 将 App 的包名填入，填入的包名将不会被 Mihomo 代理
# 注意: 包名要用双引号，每个包名之间用空格隔离开来
BLACKLIST_PACKAGE=("com.tencent.tmgp.sgame" "com.miHoYo.hkrpg" "com.miHoYo.Yuanshen" "com.ss.android.ugc.aweme" "com.ss.android.ugc.livelite" "com.larus.nova")

# 黑名单WIFI
# 将 WIFI 名称填入，检测到当前所连接 WIFI 有在名单内将停止服务，断开WIFI或连接不在名单内的WIFI，将启动服务
# 注意: WIFI名要用双引号，每个WIFI名之间用空格隔离开来，无内容则无法启动监控
BLACKLIST_WIFI=()
