# HTTP(S) 和 SOCKS 代理混合端口
mixed-port: 7890
# 透明代理端口，用于 Linux 和 MacOS
redir-port: 7891
# Linux的透明代理服务器端口（TCP和UDP）
tproxy-port: 1536
# 允许局域网连接
allow-lan: true
# 绑定 IP 地址，仅作用于 allow-lan 为 true，'*'表示所有地址
bind-address: "*"
# 代理模式 rule(规则匹配)、 global(全局代理)、 direct(全局直连)
mode: rule
# 日志级别 silent(静默)/error(仅输出发生错误至无法使用的日志)/warning(输出发生错误但不影响运行的日志)/info(输出一般运行的内容)/debug(尽可能的输出运行中所有的信息)
log-level: silent
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
ipv6: true
# 禁用 TCP Keep Alive
disable-keep-alive: true
# 进程匹配模式
find-process-mode: always
# 更新时间
updatetime: &Time 86400

# API 监听地址
external-controller: 0.0.0.0:9090
# API 访问密钥
secret: ""
# 配置 WEB UI 目录
external-ui: "webui/zashboard"
# WEB UI 下载地址
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"

# 缓存
profile:
  # 储存策略组的选择
  store-selected: true
  # 持久化 fake-ip
  store-fake-ip: true
# TCP 并发
tcp-concurrent: true
# 统一延迟时
unified-delay: true

# GEOIP 数据模式
geodata-mode: true
# GEO 文件加载模式
# standard(标准加载器)/memconservative(小内存设备优化加载器)
geodata-loader: standard
#自定 GEO 下载地址
geox-url:
  # geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  # geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  # mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
# 自动更新 GEO
geo-auto-update: false
# 更新间隔，单位：小时
geo-update-interval: 24

# 实验
experimental:
  http-headers:
    request:
      - name: "User-Agent"
        value: "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36"
      - name: "Accept-Language"
        value: "en-US,en;q=0.9"

# 健康检查
p: &p
  type: http
  interval: *Time
  health-check:
    enable: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
  proxy: 🔄 订阅更新
  header:
    User-Agent:
      - "ClashMetaForAndroid/2.11.2.Meta"
      - "clash-verge/v2.2.3"
      - "ClashforWindows/0.19.23"
      - "clash.meta"
      - "mihomo"
  exclude-filter: "套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|失联|余额|分享|免翻|邀请|地址"

# hosts
hosts:
  services.googleapis.cn: services.googleapis.com
  cn.bing.com: global.bing.com

# DNS 配置
dns:
  enable: true
  # 解析 IPV6
  ipv6: true
  # DNS 服务监听
  listen: 0.0.0.0:1053
  # DOH 优先使用 http/3
  prefer-h3: false
  # 遵循路由规则
  respect-rule: true
  #  IP 段设置
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  # DNS 处理模式 fake-ip / redir-host
  enhanced-mode: redir-host
  # 是否遵循 nameserver-policy
  direct-nameserver-follow-policy: true
  # 用于 direct 出口域名解析的 DNS 服务器
  direct-nameserver:
    - 180.184.1.1
    - 180.184.2.2
    - 119.29.29.29
    - 119.28.28.28
    - 223.6.6.6
    - 223.5.5.5
  # 代理节点域名解析服务器
  proxy-server-nameserver:
    - system
  # 指定域名查询的解析服务器
  nameserver-policy:
    "RULE-SET:domain_cn,domain_lan,domain_microsoft,domain_apple":
      - system
    "RULE-SET:domain_all_ad,domain_webrtc": "rcode://refused"
  # 默认的域名解析服务器
  nameserver:
    - https://dns.google/dns-query#🌐 DNS连接
    - https://dns.cloudflare.com/dns-query#🌐 DNS连接

# 域名嗅探
sniffer:
  # 启用
  enable: false
  # 对 redir-host 类型识别的流量进行强制嗅探
  force-dns-mapping: true
  # 对所有未获取到域名的流量进行强制嗅探
  parse-pure-ip: true
  # 嗅探的协议设置
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      # 使用嗅探结果作为实际访问
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  # 强制嗅探
  force-domain:
    - "+.v2ex.com"
  # 跳过嗅探
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    
# Tun 网卡
tun:
  enable: true
  # 模式堆栈
  stack: gvisor
  # 网卡名称
  device: Meta
  # 自动设置全局路由
  auto-route: true
  # 自动配置 iptables/nftables
  auto-redirect: false
  # 自动选择流量出口接口
  auto-detect-interface: true
  # dns 劫持
  dns-hijack: 
    - any:53
    - tcp://any:53
  # 执行严格的路由规则
  strict-route: true
  # UDP NAT 过期时间
  udp-timeout: 300
  # 启用独立于端点的 NAT
  endpoint-independent-nat: true
  # 禁用 ICMP 转发
  disable-icmp-forwarding: true

# 代理
proxies:
  - {name: 🇨🇳 国内, type: direct, udp: true}
  - {name: ⛔️ 拒绝连接, type: reject}
  - {name: 🌐 DNS劫持, type: dns}

# 代理组
proxy_groups: &proxy_groups
    type: select
    proxies:
      - "🎯 节点选择"
      - "♻️ 自动选择"
      - "⚖️ 负载均衡"
      - "↪️ 故障转移"
      - "🇭🇰 香港节点"
      - "🇼🇸 台湾节点"
      - "🇯🇵 日本节点"
      - "🇰🇷 韩国节点"
      - "🇸🇬 新加坡节点"
      - "🇨🇦 加拿大节点"
      - "🇺🇸 美国节点"
      - "🇬🇧 英国节点"
      - "🇫🇷 法国节点"
      - "🇩🇪 德国节点"
      - "🇳🇱 荷兰节点"
      - "🇮🇳 印度节点"
      - "🌀 其它节点"
      - "🛰️ 全球直连"
      - "⛔️ 拒绝连接"
CNproxy_groups: &CNproxy_groups
    type: select
    proxies:
      - "🛰️ 全球直连"
      - "🎯 节点选择"
      - "♻️ 自动选择"
      - "⚖️ 负载均衡"
      - "↪️ 故障转移"
      - "🇭🇰 香港节点"
      - "🇼🇸 台湾节点"
      - "🇯🇵 日本节点"
      - "🇰🇷 韩国节点"
      - "🇸🇬 新加坡节点"
      - "🇨🇦 加拿大节点"
      - "🇺🇸 美国节点"
      - "🇬🇧 英国节点"
      - "🇫🇷 法国节点"
      - "🇩🇪 德国节点"
      - "🇳🇱 荷兰节点"
      - "🇮🇳 印度节点"
      - "🌀 其它节点"
      - "⛔️ 拒绝连接"
proxy-groups:
  - name: "🎯 节点选择"
    type: select
    proxies:
      - "♻️ 自动选择"
      - "⚖️ 负载均衡"
      - "↪️ 故障转移"
      - "🇭🇰 香港节点"
      - "🇼🇸 台湾节点"
      - "🇯🇵 日本节点"
      - "🇰🇷 韩国节点"
      - "🇸🇬 新加坡节点"
      - "🇨🇦 加拿大节点"
      - "🇺🇸 美国节点"
      - "🇬🇧 英国节点"
      - "🇫🇷 法国节点"
      - "🇩🇪 德国节点"
      - "🇳🇱 荷兰节点"
      - "🇮🇳 印度节点"
      - "🌀 其它节点"
      - "🇨🇳 国内"
  - name: "♻️ 自动选择"
    type: url-test
    <<: *A
  - name: "⚖️ 负载均衡"
    type: load-balance
    strategy: round-robin
    <<: *A
  - name: "↪️ 故障转移"
    type: fallback
    <<: *A
  - name: "🇬 GitHub"
    <<: *proxy_groups
  - name: "🎶 TikTok"
    <<: *proxy_groups
  - name: "🌏️ 社交媒体"
    <<: *proxy_groups
  - name: "🎵 Spotify"
    <<: *proxy_groups
  - name: "📢 谷歌FCM"
    <<: *CNproxy_groups
  - name: "🇬 谷歌服务"
    <<: *proxy_groups
  - name: "🍎 苹果服务"
    <<: *CNproxy_groups
  - name: "Ⓜ️ 微软服务"
    <<: *CNproxy_groups
  - name: "⬇️ 下载服务"
    <<: *CNproxy_groups
  - name: "♥️ 特殊服务"
    <<: *proxy_groups
  - name: "🕹️ Steam"
    <<: *proxy_groups
  - name: "🤖 AI"
    <<: *proxy_groups
  - name: "🚀 测速工具"
    <<: *CNproxy_groups
  - name: "🌐 DNS连接"
    <<: *proxy_groups
  - name: "🔄 订阅更新"
    type: select
    proxies:
      - "🛰️ 全球直连"
      - "🎯 节点选择"
  - name: "🐟 漏网之鱼"
    <<: *proxy_groups
  - name: "🚫 广告拦截"
    type: select
    proxies:
      - "⛔️ 拒绝连接"
      - "🌐 DNS劫持"
      - "🛰️ 全球直连"
      - REJECT-DROP
      - PASS
  - name: "🖥️ WebRTC"
    type: select
    proxies:
      - "⛔️ 拒绝连接"
      - "🌐 DNS劫持"
      - "🛰️ 全球直连"
      - REJECT-DROP
      - PASS
  - name: "🛰️ 全球直连"
    type: select
    proxies:
      - "🇨🇳 国内"
      - "🎯 节点选择"
      - "♻️ 自动选择"
      - "⚖️ 负载均衡"
      - "↪️ 故障转移"
    exclude-filter: "🛰️ 全球直连"
  - name: "🇭🇰 香港节点"
    filter: "港|HK|hk|Hong Kong|HongKong|hongkong|深港|🇭🇰"
    <<: *All
  - name: "🇼🇸 台湾节点"
    filter: "台|新北|彰化|TW|Taiwan|🇼🇸"
    <<: *All
  - name: "🇯🇵 日本节点"
    filter: "日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵"
    <<: *All
  - name: "🇰🇷 韩国节点"
    filter: "KR|Korea|KOR|首尔|韩|韓|🇰🇷"
    <<: *All
  - name: "🇸🇬 新加坡节点"
    filter: "新加坡|坡|狮城|SG|Singapore|🇸🇬"
    <<: *All
  - name: "🇨🇦 加拿大节点"
    filter: "加拿大|多伦多|Canada|CA|渥太华|温哥华|卡尔加里|🇨🇦"
    <<: *All
  - name: "🇺🇸 美国节点"
    filter: "美|阿什本|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|🇺🇸"
    <<: *All
  - name: "🇬🇧 英国节点"
    filter: "英国|伦敦|Great Britain|United Kiongdom|GB|🇬🇧"
    <<: *All
  - name: "🇫🇷 法国节点"
    filter: "法国|France|FR|巴黎|🇫🇷"
    <<: *All
  - name: "🇩🇪 德国节点"
    filter: "德国|Germany|DE|柏林|法兰克福|🇩🇪"
    <<: *All
  - name: "🇳🇱 荷兰节点"
    filter: "荷兰|Netherlands|NL|阿姆斯特丹|🇳🇱"
    <<: *All
  - name: "🇮🇳 印度节点"
    filter: "印度|孟买|海得拉巴|India|IN|🇮🇳"
    <<: *All
  - name: "🌀 其它节点"
    exclude-filter: "港|HK|hk|Hong Kong|HongKong|hongkong|深港|🇭🇰|台|新北|彰化|TW|Taiwan|🇼🇸|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵|KR|Korea|KOR|首尔|韩|韓|🇰🇷|新加坡|坡|狮城|SG|Singapore|🇸🇬|加拿大|多伦多|Canada|CA|渥太华|温哥华|卡尔加里|🇨🇦|美|阿什本|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|🇺🇸|英国|伦敦|Great Britain|United Kiongdom|GB|🇬🇧|法国|France|FR|巴黎|🇫🇷|德国|Germany|DE|柏林|法兰克福|🇩🇪|荷兰|Netherlands|NL|阿姆斯特丹|🇳🇱|印度|孟买|海得拉巴|India|IN|🇮🇳"
    <<: *All

# 规则集合
rule-anchor:
  local: &local {type: file, behavior: classical, format: text}
  classical: &classical {type: http, behavior: classical, format: text, interval: *Time}
  ip: &ip {type: http, behavior: ipcidr, format: mrs, interval: *Time}
  domain: &domain {type: http, behavior: domain, format: mrs, interval: *Time}
  domain_text: &domain_text {type: http, behavior: domain, format: text, interval: *Time}
rule-providers:
  # 用户自定义直连
  classical_user_direct:
    <<: *local
    path: "./rule_provider/classical_user_direct.list"
  
  # 直连
  domain_all_direct:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Direct/Domain_ALL_Direct.mrs"
    path: "./rule_provider/Domain_ALL_Direct.mrs"
    
  # 特殊服务
  domain_special:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Special/Domain_Special.mrs"
    path: "./rule_provider/Domain_Special.mrs"
    
  # 下载服务
  domain_download:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Download/Domain_Download.mrs"
    path: "./rule_provider/Domain_Download.mrs"
    
  # 广告
  domain_all_ad:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Ads/Domain_All_AD.mrs"
    path: "./rule_provider/Domain_All_AD.mrs"
  ip_custom_ad:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Ads/IP_Custom.mrs"
    path: "./rule_provider/IP_Custom.mrs"
    
  # WebRTC
  domain_webrtc:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/WebRTC/Domain_WebRTC.mrs"
    path: "./rule_provider/Domain_WebRTC.mrs"
    
  # fakeip-filter
  fakeip-filter:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/FakeipFilter/Domain_FakeipFilter.mrs"
    path: "./rule_provider/fakeip-filter.mrs"
        
  # 抖音
  domain_douyin:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/DouYin/Domain_DouYin.mrs"
    path: "./rule_provider/Domain_DouYin.mrs"
        
  # 哔哩哔哩
  domain_bilibili:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/BiliBili/Domain_BiliBili.mrs"
    path: "./rule_provider/Domain_BiliBili.mrs"
  ip_bilibili:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/BiliBili/IP_BiliBili.mrs"
    path: "./rule_provider/IP_BiliBili.mrs"
    
  # PT
  domain_pt:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/PT/Domain_PT.mrs"
    path: "./rule_provider/Domain_PT.mrs"
  ip_pt:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/PT/IP_PT.mrs"
    path: "./rule_provider/IP_PT.mrs"
    
  # Steam 
  domain_steam:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Steam/Domain_Steam.mrs"
    path: "./rule_provider/Domain_Steam.mrs"
  domain_steam_cn:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Steam/Domain_SteamCN.mrs"
    path: "./rule_provider/Domain_SteamCN.mrs"
    
  # Speedtest
  domain_speedtest:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Speedtest/Domain_Speedtest.mrs"
    path: "./rule_provider/Domain_Speedtest.mrs"
    
  # GitHub
  domain_github:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/GitHub/Domain_GitHub.mrs"
    path: "./rule_provider/Domain_GitHub.mrs"
    
  # TikTok
  domain_tiktok:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/TikTok/Domain_TikTok.mrs"
    path: "./rule_provider/Domain_TikTok.mrs"
    
  # Discord
  domain_discord:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Discord/Domain_Discord.mrs"
    path: "./rule_provider/Domain_Discord.mrs"
    
  # YouTube
  domain_youtube:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/YouTube/Domain_YouTube.mrs"
    path: "./rule_provider/Domain_YouTube.mrs"
  ip_youtube:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/YouTube/IP_YouTube.mrs"
    path: "./rule_provider/IP_YouTube.mrs"
    
  # Facebook
  domain_facebook:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Facebook/Domain_Facebook.mrs"
    path: "./rule_provider/Domain_Facebook.mrs"
  ip_facebook:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Facebook/IP_Facebook.mrs"
    path: "./rule_provider/IP_Facebook.mrs"
    
  # Twitter
  domain_twitter:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Twitter/Domain_Twitter.mrs"
    path: "./rule_provider/Domain_Twitter.mrs"
  ip_twitter:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Twitter/IP_Twitter.mrs"
    path: "./rule_provider/IP_Twitter.mrs"
    
  # Netflix
  domain_netflix:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Netflix/Domain_Netflix.mrs"
    path: "./rule_provider/Domain_Netflix.mrs"
  ip_netflix:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Netflix/IP_Netflix.mrs"
    path: "./rule_provider/IP_Netflix.mrs"
    
  # Telegram
  domain_telegram:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Telegram/Domain_Telegram.mrs"
    path: "./rule_provider/Domain_Telegram.mrs"
  ip_telegram:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Telegram/IP_Telegram.mrs"
    path: "./rule_provider/IP_Telegram.mrs"
    
  # OpenAI
  domain_openai:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/OpenAI/Domain_OpenAI.mrs"
    path: "./rule_provider/Domain_OpenAI.mrs"
  ip_openai:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/OpenAI/IP_OpenAI.mrs"
    path: "./rule_provider/IP_OpenAI.mrs"
    
  # Spotify
  domain_spotify:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Spotify/Domain_Spotify.mrs"
    path: "./rule_provider/Domain_Spotify.mrs"
  ip_spotify:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Spotify/IP_Spotify.mrs"
    path: "./rule_provider/IP_Spotify.mrs"
    
  # Proxy
  domain_proxy:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Proxy/Domain_Proxy.mrs"
    path: "./rule_provider/Domain_Proxy.mrs"
  ip_proxy:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Proxy/IP_Proxy.mrs"
    path: "./rule_provider/IP_Proxy.mrs"
    
  # Google FCM
  domain_googlefcm:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/GoogleFCM/Domain_GoogleFCM.mrs"
    path: "./rule_provider/Domain_GoogleFCM.mrs"
  ip_googlefcm:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/GoogleFCM/IP_GoogleFCM.mrs"
    path: "./rule_provider/IP_GoogleFCM.mrs"
    
  # Google
  domain_google:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Google/Domain_Google.mrs"
    path: "./rule_provider/Domain_Google.mrs"
  ip_google:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Google/IP_Google.mrs"
    path: "./rule_provider/IP_Google.mrs"
    
  # Apple
  domain_apple:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Apple/Domain_Apple.mrs"
    path: "./rule_provider/Domain_Apple.mrs"
  ip_apple:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Apple/IP_Apple.mrs"
    path: "./rule_provider/IP_Apple.mrs"
    
  # Microsoft
  domain_microsoft:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Microsoft/Domain_Microsoft.mrs"
    path: "./rule_provider/Domain_Microsoft.mrs"

  # Lan
  domain_lan:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Lan/Domain_Lan.mrs"
    path: "./rule_provider/Domain_Lan.mrs"
  ip_lan:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/Lan/IP_Lan.mrs"
    path: "./rule_provider/IP_Lan.mrs"    

  # CN
  domain_cn:
    <<: *domain
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/CN/Domain_CN.mrs"
    path: "./rule_provider/Domain_CN.mrs"
  ip_cn:
    <<: *ip
    url: "https://github.com/5MayRain/Rule/raw/main/Mihomo/CN/IP_CN.mrs"
    path: "./rule_provider/IP_CN.mrs"

# 规则
rules:
  - "AND,((DST-PORT,443),(NETWORK,UDP),(DOMAIN-KEYWORD,mtalk)),⛔️ 拒绝连接"
  
  - "DST-PORT,53,🌐 DNS劫持"
  - "DST-PORT,853,🌐 DNS连接"
  
  - "RULE-SET,classical_user_direct,🛰️ 全球直连"
  - "RULE-SET,domain_all_direct,🛰️ 全球直连"
  
  - "RULE-SET,domain_all_ad,🚫 广告拦截"
  - "RULE-SET,ip_custom_ad,🚫 广告拦截,no-resolve"

  - "RULE-SET,domain_webrtc,🖥️ WebRTC"
  - "DST-PORT,3478/5349-5350/10000/19302,🖥️ WebRTC"

  - "RULE-SET,domain_douyin,🛰️ 全球直连"
    
  - "RULE-SET,domain_bilibili,🛰️ 全球直连"
  - "RULE-SET,ip_bilibili,🛰️ 全球直连,no-resolve"
  
  - "RULE-SET,domain_download,⬇️ 下载服务"
  - "RULE-SET,domain_pt,⬇️ 下载服务"
  - "RULE-SET,ip_pt,⬇️ 下载服务,no-resolve"
    
  - "RULE-SET,domain_special,♥️ 特殊服务"
  
  - "RULE-SET,domain_steam,🕹️ Steam"
  - "RULE-SET,domain_steam_cn,🛰️ 全球直连"

  - "RULE-SET,domain_speedtest,🚀 测速工具"

  - "RULE-SET,domain_github,🇬 GitHub"

  - "RULE-SET,domain_tiktok,🎶 TikTok"
  
  - "RULE-SET,domain_discord,🌏️ 社交媒体"
  - "RULE-SET,domain_youtube,🌏️ 社交媒体"
  - "RULE-SET,ip_youtube,🌏️ 社交媒体,no-resolve"
  - "RULE-SET,domain_facebook,🌏️ 社交媒体"
  - "RULE-SET,ip_facebook,🌏️ 社交媒体,no-resolve"
  - "RULE-SET,domain_twitter,🌏️ 社交媒体"
  - "RULE-SET,ip_twitter,🌏️ 社交媒体,no-resolve"
  - "RULE-SET,domain_netflix,🌏️ 社交媒体"
  - "RULE-SET,ip_netflix,🌏️ 社交媒体,no-resolve"
  - "RULE-SET,domain_telegram,🌏️ 社交媒体"
  - "RULE-SET,ip_telegram,🌏️ 社交媒体,no-resolve"

  - "RULE-SET,domain_openai,🤖 AI"
  - "RULE-SET,ip_openai,🤖 AI,no-resolve"
    
  - "RULE-SET,domain_spotify,🎵 Spotify"
  - "RULE-SET,ip_spotify,🎵 Spotify,no-resolve"

  - "DST-PORT,5228-5230,📢 谷歌FCM"
  - "RULE-SET,domain_googlefcm,📢 谷歌FCM"
  - "RULE-SET,ip_googlefcm,📢 谷歌FCM,no-resolve"
  
  - "RULE-SET,domain_google,🇬 谷歌服务"
  - "RULE-SET,ip_google,🇬 谷歌服务,no-resolve"
    
  - "RULE-SET,domain_apple,🍎 苹果服务"
  - "RULE-SET,ip_apple,🍎 苹果服务,no-resolve"

  - "RULE-SET,domain_microsoft,Ⓜ️ 微软服务"
  
  - "RULE-SET,domain_proxy,🎯 节点选择"
  - "RULE-SET,ip_proxy,🎯 节点选择,no-resolve"
   
  - "RULE-SET,domain_lan,🛰️ 全球直连"
  - "RULE-SET,ip_lan,🛰️ 全球直连,no-resolve"
  - "RULE-SET,domain_cn,🛰️ 全球直连"
  - "RULE-SET,ip_cn,🛰️ 全球直连,no-resolve"

  - "MATCH,🐟 漏网之鱼"