 # HTTP(S) 和 SOCKS 代理混合端口
mixed-port: 7890
# 透明代理端口，用于 Linux 和 MacOS
redir-port: 7891
# Linux的透明代理服务器端口（TCP和UDP）
tproxy-port: 1536
# 允许局域网连接
allow-lan: true
# 绑定 IP 地址，仅作用于 allow-lan 为 true，'*'表示所有地址
bind-address: "*"
# 代理模式 rule(规则匹配)、 global(全局代理)、 direct(全局直连)
mode: rule
# 日志级别 silent(静默)/error(仅输出发生错误至无法使用的日志)/warning(输出发生错误但不影响运行的日志)/info(输出一般运行的内容)/debug(尽可能的输出运行中所有的信息)
log-level: silent
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
ipv6: true
# 禁用 TCP Keep Alive
disable-keep-alive: true
# 进程匹配模式
find-process-mode: always
# 更新时间
updatetime: &Time 10800

# API 监听地址
external-controller: 0.0.0.0:9090
# API 访问密钥
secret: ""
# 配置 WEB UI 目录
external-ui: "webui/zashboard"
# WEB UI 下载地址
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"

# 缓存
profile:
  # 储存策略组的选择
  store-selected: true
  # 持久化 fake-ip
  store-fake-ip: true
# TCP 并发
tcp-concurrent: true
# 统一延迟时
unified-delay: true

# GEOIP 数据模式
geodata-mode: true
# GEO 文件加载模式
# standard(标准加载器)/memconservative(小内存设备优化加载器)
geodata-loader: standard
#自定 GEO 下载地址
geox-url:
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
# 自动更新 GEO
geo-auto-update: true
# 更新间隔，单位：小时
geo-update-interval: 24

# 健康检查
p: &p
  type: http
  interval: *Time
  health-check:
    enable: true
    url: "https://www.gstatic.com/generate_204"
    interval: 300
  proxy: "订阅更新"
  header:
    User-Agent:
      - "ClashMetaForAndroid/2.11.2.Meta"
      - "clash-verge/v2.2.3"
      - "ClashforWindows/0.19.23"
      - "clash.meta"
      - "mihomo"
  exclude-filter: "套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|失联|余额|分享|免翻|邀请|地址"

# hosts
hosts:
  services.googleapis.cn: services.googleapis.com
  cn.bing.com: global.bing.com

# DNS 配置
dns:
  enable: true
  # 解析 IPV6
  ipv6: true
  # DNS 服务监听
  listen: 0.0.0.0:1053
  # DOH 优先使用 http/3
  prefer-h3: false
  #  IP 段设置
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::/64
  # DNS 处理模式 fake-ip / redir-host
  enhanced-mode: redir-host
  # 用于 direct 出口域名解析的 DNS 服务器
  direct-nameserver:
    - system
  # 代理节点域名解析服务器
  proxy-server-nameserver:
    - system
  # 指定域名查询的解析服务器
  nameserver-policy:
    "RULE-SET:Domain_Lan,Domain_CN,Domain_Microsoft,Domain_Apple":
      - system
    "RULE-SET:Domain_Advertising": "rcode://refused"
  # 默认的域名解析服务器
  nameserver:
    - https://8.8.8.8:443/dns-query#DNS连接
    - https://8.8.4.4:443/dns-query#DNS连接
    - https://1.1.1.1:443/dns-query#DNS连接
    - https://1.0.0.1:443/dns-query#DNS连接

# 域名嗅探
sniffer:
  # 启用
  enable: true
  # 对 redir-host 类型识别的流量进行强制嗅探
  force-dns-mapping: true
  # 对所有未获取到域名的流量进行强制嗅探
  parse-pure-ip: true
  # 使用嗅探结果作为实际访问
  override-destination: false
  # 嗅探的协议设置
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      # 使用嗅探结果作为实际访问
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  # 强制嗅探
  force-domain:
    - "+.v2ex.com"
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  # 跳过嗅探
  skip-domain:
    - "Mijia Cloud"
    - "+.io.mi.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.apple.com"
    - "+.push.apple.com"
    
# Tun 网卡
tun:
  enable: true
  # 模式堆栈
  stack: gvisor
  # 网卡名称
  device: Meta
  # 自动设置全局路由
  auto-route: true
  # 自动配置 iptables/nftables
  auto-redirect: false
  # 自动选择流量出口接口
  auto-detect-interface: true
  # dns 劫持
  dns-hijack: 
    - any:53
    - tcp://any:53
  # 执行严格的路由规则
  strict-route: true
  # UDP NAT 过期时间
  udp-timeout: 300
  # 路由表索引
  iproute2-table-index: 2022
  # 规则起始索引
  iproute2-rule-index: 9000
  # 启用独立于端点的 NAT
  endpoint-independent-nat: true
  # 禁用 ICMP 转发
  disable-icmp-forwarding: true

# 代理
proxies:
  - {name: "国内", type: direct, udp: true}
  - {name: "拒绝连接", type: reject}
  - {name: "DNS劫持", type: dns}

# 代理组
proxy_groups: &proxy_groups
    type: select
    proxies:
      - "节点选择"
      - "自动选择"
      - "负载均衡"
      - "故障转移"
      - "香港节点"
      - "台湾节点"
      - "日本节点"
      - "韩国节点"
      - "新加坡节点"
      - "加拿大节点"
      - "美国节点"
      - "英国节点"
      - "法国节点"
      - "德国节点"
      - "荷兰节点"
      - "印度节点"
      - "其它节点"
      - "全球直连"
      - "拒绝连接"

cn_groups: &cn_groups
    type: select
    proxies:
      - "全球直连"
      - "节点选择"
      - "自动选择"
      - "负载均衡"
      - "故障转移"
      - "香港节点"
      - "台湾节点"
      - "日本节点"
      - "韩国节点"
      - "新加坡节点"
      - "加拿大节点"
      - "美国节点"
      - "英国节点"
      - "法国节点"
      - "德国节点"
      - "荷兰节点"
      - "印度节点"
      - "其它节点"
      - "拒绝连接"
proxy-groups:
  - name: "节点选择"
    type: select
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/sub_select.svg"
    proxies:
      - "自动选择"
      - "负载均衡"
      - "故障转移"
      - "香港节点"
      - "台湾节点"
      - "日本节点"
      - "韩国节点"
      - "新加坡节点"
      - "加拿大节点"
      - "美国节点"
      - "英国节点"
      - "法国节点"
      - "德国节点"
      - "荷兰节点"
      - "印度节点"
      - "其它节点"
      - "国内"
  - name: "自动选择"
    type: url-test
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/auto_select.svg"
    <<: *A
  - name: "负载均衡"
    type: load-balance
    strategy: round-robin
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/load_balance.svg"
    <<: *A
  - name: "故障转移"
    type: fallback
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/fallback.svg"
    <<: *A
  - name: "GitHub"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/github.svg"
    <<: *proxy_groups
  - name: "社交媒体"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/network.svg"
    <<: *proxy_groups
  - name: "谷歌FCM"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/google.svg"
    <<: *cn_groups
  - name: "谷歌服务"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/google.svg"
    <<: *proxy_groups
  - name: "苹果服务"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/apple.svg"
    <<: *cn_groups
  - name: "微软服务"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/microsoft.svg"
    <<: *cn_groups
  - name: "特殊服务"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/love.svg"
    <<: *proxy_groups
  - name: "下载服务"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/download.svg"
    <<: *cn_groups
  - name: "Steam"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/steam.svg"
    <<: *proxy_groups
  - name: "AI"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/robot.svg"
    <<: *proxy_groups
  - name: "测速工具"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/speed_test.svg"
    <<: *cn_groups
  - name: "DNS连接"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/dns.svg"
    <<: *proxy_groups
  - name: "订阅更新"
    type: select
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/update.svg"
    proxies:
      - "全球直连"
      - "节点选择"
  - name: "WebRTC"
    type: select
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/browser.svg"
    proxies:
      - "拒绝连接"
      - "DNS劫持"
      - REJECT-DROP
      - PASS
  - name: "广告拦截"
    type: select
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/reject.svg"
    proxies:
      - "拒绝连接"
      - "DNS劫持"
      - REJECT-DROP
      - PASS
  - name: "全球直连"
    type: select
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/earth.svg"
    proxies:
      - "国内"
      - "节点选择"
      - "自动选择"
      - "负载均衡"
      - "故障转移"
  - name: "漏网之鱼"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/fish.svg"
    <<: *proxy_groups
  - name: "香港节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/hk.svg"
    filter: "港|HK|hk|Hong Kong|HongKong|hongkong|深港|🇭🇰"
    <<: *All
  - name: "台湾节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/tw.svg"
    filter: "台|新北|彰化|TW|Taiwan|🇼🇸"
    <<: *All
  - name: "日本节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/jp.svg"
    filter: "日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵"
    <<: *All
  - name: "韩国节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/kr.svg"
    filter: "KR|Korea|KOR|首尔|韩|韓|🇰🇷"
    <<: *All
  - name: "新加坡节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/sg.svg"
    filter: "新加坡|坡|狮城|SG|Singapore|🇸🇬"
    <<: *All
  - name: "加拿大节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/ca.svg"
    filter: "加拿大|多伦多|Canada|CA|渥太华|温哥华|卡尔加里|🇨🇦"
    <<: *All
  - name: "美国节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/us.svg"
    filter: "美|阿什本|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|🇺🇸"
    <<: *All
  - name: "英国节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/gb.svg"
    filter: "英国|伦敦|Great Britain|United Kiongdom|GB|🇬🇧"
    <<: *All
  - name: "法国节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/fr.svg"
    filter: "法国|France|FR|巴黎|🇫🇷"
    <<: *All
  - name: "德国节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/de.svg"
    filter: "德国|Germany|DE|柏林|法兰克福|🇩🇪"
    <<: *All
  - name: "荷兰节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/nl.svg"
    filter: "荷兰|Netherlands|NL|阿姆斯特丹|🇳🇱"
    <<: *All
  - name: "印度节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/in.svg"
    filter: "印度|孟买|海得拉巴|India|IN|🇮🇳"
    <<: *All
  - name: "其它节点"
    icon: "https://cdn.jsdelivr.net/gh/5MayRain/rule@main/icon/other.svg"
    exclude-filter: "港|HK|hk|Hong Kong|HongKong|hongkong|深港|🇭🇰|台|新北|彰化|TW|Taiwan|🇼🇸|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|🇯🇵|KR|Korea|KOR|首尔|韩|韓|🇰🇷|新加坡|坡|狮城|SG|Singapore|🇸🇬|加拿大|多伦多|Canada|CA|渥太华|温哥华|卡尔加里|🇨🇦|美|阿什本|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|🇺🇸|英国|伦敦|Great Britain|United Kiongdom|GB|🇬🇧|法国|France|FR|巴黎|🇫🇷|德国|Germany|DE|柏林|法兰克福|🇩🇪|荷兰|Netherlands|NL|阿姆斯特丹|🇳🇱|印度|孟买|海得拉巴|India|IN|🇮🇳"
    <<: *All

# 规则集合
rule-anchor:
  local: &local {type: file, behavior: classical, format: text}
  classical: &classical {type: http, behavior: classical, format: text, interval: *Time}
  ip: &ip {type: http, behavior: ipcidr, format: mrs, interval: *Time}
  domain: &domain {type: http, behavior: domain, format: mrs, interval: *Time}
  
rule-providers:
  # 用户自定义
  Classical_User_Direct:
    <<: *local
    path: "./rule_provider/Classical_User_Direct.list"
  Classical_User_Proxy:
    <<: *local
    path: "./rule_provider/Classical_User_Proxy.list"
  Classical_User_Reject:
    <<: *local
    path: "./rule_provider/Classical_User_Reject.list"

  # 局域网
  Domain_Lan:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Lan/Domain_Lan.mrs"
    path: "./rule_provider/Domain_Lan.mrs"
  IP_Lan:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Lan/IP_Lan.mrs"
    path: "./rule_provider/IP_Lan.mrs"
  # 国内
  Domain_CN:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/ChinaMax/Domain_ChinaMax.mrs"
    path: "./rule_provider/Domain_CN.mrs"
  IP_CN:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/ChinaMax/IP_ChinaMax.mrs"
    path: "./rule_provider/IP_CN.mrs"
  # 直连
  Domain_Direct:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Direct/Domain_Direct.mrs"
    path: "./rule_provider/Domain_Direct.mrs"
    
  # 谷歌
  Domain_Google:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Google/Domain_Google.mrs"
    path: "./rule_provider/Domain_Google.mrs"
  IP_Google:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Google/IP_Google.mrs"
    path: "./rule_provider/IP_Google.mrs"
  Domain_GoogleFCM:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/GoogleFCM/Domain_GoogleFCM.mrs"
    path: "./rule_provider/Domain_GoogleFCM.mrs"
  IP_GoogleFCM:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/GoogleFCM/IP_GoogleFCM.mrs"
    path: "./rule_provider/IP_GoogleFCM.mrs"
  # 苹果
  Domain_Apple:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Apple/Domain_Apple.mrs"
    path: "./rule_provider/Domain_Apple.mrs"
  IP_Apple:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Apple/IP_Apple.mrs"
    path: "./rule_provider/IP_Apple.mrs"
  # 微软
  Domain_Microsoft:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Microsoft/Domain_Microsoft.mrs"
    path: "./rule_provider/Domain_Microsoft.mrs"
    
  # Discord
  Domain_Discord:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Discord/Domain_Discord.mrs"
    path: "./rule_provider/Domain_Discord.mrs"
  # Facebook
  Domain_Facebook:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Facebook/Domain_Facebook.mrs"
    path: "./rule_provider/Domain_Facebook.mrs"
  IP_Facebook:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Facebook/IP_Facebook.mrs"
    path: "./rule_provider/IP_Facebook.mrs"
  # Instagram
  Domain_Instagram:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Instagram/Domain_Instagram.mrs"
    path: "./rule_provider/Domain_Instagram.mrs"
  # Netflix
  Domain_Netflix:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Netflix/Domain_Netflix.mrs"
    path: "./rule_provider/Domain_Netflix.mrs"
  IP_Netflix:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Netflix/IP_Netflix.mrs"
    path: "./rule_provider/IP_Netflix.mrs"
  # Spotify
  Domain_Spotify:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Spotify/Domain_Spotify.mrs"
    path: "./rule_provider/Domain_Spotify.mrs"
  IP_Spotify:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Spotify/IP_Spotify.mrs"
    path: "./rule_provider/IP_Spotify.mrs"
  # Telegram
  Domain_Telegram:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Telegram/Domain_Telegram.mrs"
    path: "./rule_provider/Domain_Telegram.mrs"
  IP_Telegram:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Telegram/IP_Telegram.mrs"
    path: "./rule_provider/IP_Telegram.mrs"
  # TikTok
  Domain_TikTok:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/TikTok/Domain_TikTok.mrs"
    path: "./rule_provider/Domain_TikTok.mrs"
  # YouTube
  Domain_YouTube:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/YouTube/Domain_YouTube.mrs"
    path: "./rule_provider/Domain_YouTube.mrs"
  IP_YouTube:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/YouTube/IP_YouTube.mrs"
    path: "./rule_provider/IP_YouTube.mrs"
    
  # OpenAI
  Domain_OpenAI:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/OpenAI/Domain_OpenAI.mrs"
    path: "./rule_provider/Domain_OpenAI.mrs"
  IP_OpenAI:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/OpenAI/IP_OpenAI.mrs"
    path: "./rule_provider/IP_OpenAI.mrs"
  # GitHub
  Domain_GitHub:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/GitHub/Domain_GitHub.mrs"
    path: "./rule_provider/Domain_GitHub.mrs"
  # PikPak
  Domain_PikPak:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/PikPak/Domain_PikPak.mrs"
    path: "./rule_provider/Domain_PikPak.mrs"
  # PT
  Domain_PT:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/PrivateTracker/Domain_PrivateTracker.mrs"
    path: "./rule_provider/Domain_PT.mrs"
  IP_PT:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/PrivateTracker/IP_PrivateTracker.mrs"
    path: "./rule_provider/IP_PT.mrs"
  # Speedtest
  Domain_Speedtest:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Speedtest/Domain_Speedtest.mrs"
    path: "./rule_provider/Domain_Speedtest.mrs"
  # Steam
  Domain_Steam:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Steam/Domain_Steam.mrs"
    path: "./rule_provider/Domain_Steam.mrs"
  Domain_Steam_CN:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/SteamCN/Domain_SteamCN.mrs"
    path: "./rule_provider/Domain_Steam_CN.mrs"
    
  # Global
  Domain_Global:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Global/Domain_Global.mrs"
    path: "./rule_provider/Domain_Global.mrs"
  IP_Global:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Global/IP_Global.mrs"
    path: "./rule_provider/IP_Global.mrs"
    
  # fakeip-filter
  Domain_FakeipFilter:
    <<: *domain
    url: "https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/fakeip-filter.mrs"
    path: "./rule_provider/Domain_FakeipFilter.mrs"
    
  # WebRTC
  Classical_WebRTC:
    <<: *classical
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/STUN/Classical_STUN.list"
    path: "./rule_provider/Classical_WebRTC.list"
    
  # 广告
  Domain_Advertising:
    <<: *domain
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Advertising/Domain_Advertising.mrs"
    path: "./rule_provider/Domain_Advertising.mrs"
  IP_Advertising:
    <<: *ip
    url: "https://github.com/5MayRain/rule/raw/main/rule/Mihomo/Advertising/IP_Advertising.mrs"
    path: "./rule_provider/IP_Advertising.mrs"

# 规则
rules:
  - "AND,((DST-PORT,443),(NETWORK,UDP),(DOMAIN-KEYWORD,mtalk)),拒绝连接"

  - "DST-PORT,53,DNS劫持"
  - "DST-PORT,853,DNS连接"
  
  - "RULE-SET,Classical_User_Direct,全球直连"
  - "RULE-SET,Classical_User_Proxy,特殊服务"
  - "RULE-SET,Classical_User_Reject,广告拦截"
  
  - "RULE-SET,Domain_Advertising,广告拦截"
  - "RULE-SET,IP_Advertising,广告拦截,no-resolve"
  
  - "RULE-SET,Classical_WebRTC,WebRTC"
  
  - "RULE-SET,Domain_Lan,国内"
  - "RULE-SET,IP_Lan,国内,no-resolve"
  
  - "RULE-SET,Domain_PikPak,下载服务"
  - "DOMAIN-SUFFIX,mypikpak.com,下载服务"
  - "RULE-SET,Domain_PT,下载服务"
  - "RULE-SET,IP_PT,下载服务"
  
  - "RULE-SET,Domain_Steam,Steam"
  - "RULE-SET,Domain_Steam_CN,全球直连"

  - "RULE-SET,Domain_Speedtest,测速工具"

  - "RULE-SET,Domain_GitHub,GitHub"

  - "RULE-SET,Domain_Discord,社交媒体"
  - "RULE-SET,Domain_Facebook,社交媒体"
  - "RULE-SET,IP_Facebook,社交媒体,no-resolve"
  - "RULE-SET,Domain_Instagram,社交媒体"
  - "RULE-SET,Domain_Netflix,社交媒体"
  - "RULE-SET,IP_Netflix,社交媒体,no-resolve"
  - "RULE-SET,Domain_Spotify,社交媒体"
  - "RULE-SET,IP_Spotify,社交媒体,no-resolve"
  - "RULE-SET,Domain_Telegram,社交媒体"
  - "RULE-SET,IP_Telegram,社交媒体,no-resolve"
  - "RULE-SET,Domain_TikTok,社交媒体"
  - "RULE-SET,Domain_YouTube,社交媒体"
  - "RULE-SET,IP_YouTube,社交媒体,no-resolve"

  - "RULE-SET,Domain_OpenAI,AI"
  - "RULE-SET,IP_OpenAI,AI"

  - "DST-PORT,5228-5230,谷歌FCM"
  - "RULE-SET,Domain_GoogleFCM,谷歌FCM"
  - "RULE-SET,IP_GoogleFCM,谷歌FCM,no-resolve"
  
  - "RULE-SET,Domain_Google,谷歌服务"
  - "RULE-SET,IP_Google,谷歌服务,no-resolve"
    
  - "RULE-SET,Domain_Apple,苹果服务"
  - "RULE-SET,IP_Apple,苹果服务,no-resolve"

  - "RULE-SET,Domain_Microsoft,微软服务"
  
  - "RULE-SET,Domain_Global,节点选择"
  - "RULE-SET,IP_Global,节点选择,no-resolve"

  - "RULE-SET,Domain_CN,国内"
  - "RULE-SET,IP_CN,国内,no-resolve"
  - "RULE-SET,Domain_Direct,国内"

  - "MATCH,漏网之鱼"